# Generated by Django 5.1.5 on 2025-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('email', models.CharField(max_length=11)),
                ('Password', models.CharField(max_length=50)),
                ('Confirmpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
