# Generated by Django 5.1.5 on 2025-01-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Confirmpassword',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Password',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Username',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='PhoneNumber',
        ),
    ]
