# Generated by Django 5.1.5 on 2025-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
