# Generated by Django 5.1.5 on 2025-01-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_register_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
